// Masso G3 Post-Processor
// Generates Fanuc-dialect G-code compatible with Masso G3 controller

export const DEFAULT_POST_CONFIG = {
  name: 'Masso G3',
  units: 'mm',             // mm or inch
  coolant: 'off',          // off, flood, mist, thru
  spindleDelay: 3,         // seconds to wait after M3
  programNumbering: true,
  lineNumbering: true,
  lineIncrement: 10,
  decimals: 3,
  safeZ: 25.0,
  rapidFeed: '',           // blank = G0 (machine max)
  programHeader: '',
  programFooter: '',
  toolChangeZ: 50.0,
  homeAtEnd: false,
  homeX: 0,
  homeY: 0,
};

export function generateGcode(operations, postConfig = {}) {
  const cfg = { ...DEFAULT_POST_CONFIG, ...postConfig };
  const lines = [];
  let lineNum = 10;
  let currentTool = null;
  let currentSpindle = 0;
  let currentFeed = 0;
  let currentZ = null;
  let modalG = null;

  function n() {
    if (!cfg.lineNumbering) return '';
    const s = `N${lineNum} `;
    lineNum += cfg.lineIncrement;
    return s;
  }

  function fmt(val) {
    return val.toFixed(cfg.decimals);
  }

  function emit(line) {
    lines.push(line);
  }

  // ── Program Header ──────────────────────────────────────────────────────────
  emit('%');
  if (cfg.programNumbering) emit('O0001 (MassoCAM)');
  emit(`(Generated by MassoCAM - ${new Date().toLocaleString()})`);
  emit(`(Units: ${cfg.units === 'mm' ? 'Metric' : 'Imperial'})`);
  emit('');
  emit(`${n()}${cfg.units === 'mm' ? 'G21' : 'G20'} (${cfg.units === 'mm' ? 'Metric' : 'Imperial'} mode)`);
  emit(`${n()}G90 (Absolute positioning)`);
  emit(`${n()}G17 (XY plane)`);
  emit(`${n()}G94 (Feed per minute)`);
  emit(`${n()}G49 G40 (Cancel tool length + cutter comp)`);
  emit(`${n()}G80 (Cancel canned cycles)`);

  if (cfg.programHeader) {
    emit('');
    emit(`(--- Custom Header ---)`);
    for (const hLine of cfg.programHeader.split('\n')) emit(hLine);
  }

  // ── Operations ─────────────────────────────────────────────────────────────
  for (const op of operations) {
    if (!op.enabled) continue;
    const { toolpath, tool, params } = op;
    if (!toolpath || !toolpath.moves || toolpath.moves.length === 0) continue;

    emit('');
    emit(`(--- Operation: ${op.name} ---)`);
    emit(`(Type: ${op.type} | Tool: ${tool?.name || 'Unknown'})`);
    if (toolpath.warnings?.length > 0) {
      for (const w of toolpath.warnings) emit(`(WARNING: ${w})`);
    }

    // Tool change if needed
    if (tool && tool.id !== currentTool) {
      emit('');
      emit(`(Tool Change: T${tool.toolNumber || 1} - ${tool.name})`);
      emit(`${n()}G0 Z${fmt(cfg.toolChangeZ)} (Retract for tool change)`);
      emit(`${n()}M5 (Spindle off)`);
      if (cfg.coolant !== 'off') emit(`${n()}M9 (Coolant off)`);
      emit(`${n()}T${tool.toolNumber || 1} M6 (Tool change)`);
      currentTool = tool.id;
      currentSpindle = 0;
    }

    // Spindle on
    const rpm = params?.spindleRpm || tool?.feeds?.[0]?.spindle_rpm || 18000;
    if (rpm !== currentSpindle) {
      emit(`${n()}S${rpm} M3 (Spindle on CW)`);
      if (cfg.spindleDelay > 0) emit(`${n()}G4 P${cfg.spindleDelay * 1000} (Spindle ramp-up delay)`);
      currentSpindle = rpm;
    }

    // Coolant
    if (cfg.coolant === 'flood') emit(`${n()}M8 (Flood coolant on)`);
    else if (cfg.coolant === 'mist') emit(`${n()}M7 (Mist coolant on)`);

    // Moves
    for (const move of toolpath.moves) {
      switch (move.type) {
        case 'rapid': {
          const parts = ['G0'];
          if (move.x !== undefined) parts.push(`X${fmt(move.x)}`);
          if (move.y !== undefined) parts.push(`Y${fmt(move.y)}`);
          if (move.z !== undefined) parts.push(`Z${fmt(move.z)}`);
          emit(`${n()}${parts.join(' ')}`);
          modalG = 'G0';
          break;
        }
        case 'feed': {
          const parts = [];
          if (modalG !== 'G1') { parts.push('G1'); modalG = 'G1'; }
          if (move.x !== undefined) parts.push(`X${fmt(move.x)}`);
          if (move.y !== undefined) parts.push(`Y${fmt(move.y)}`);
          if (move.z !== undefined) parts.push(`Z${fmt(move.z)}`);
          if (move.f !== undefined && move.f !== currentFeed) {
            parts.push(`F${Math.round(move.f)}`);
            currentFeed = move.f;
          }
          if (parts.length > (modalG === 'G1' ? 0 : 1)) emit(`${n()}${parts.join(' ')}`);
          break;
        }
        case 'arc_cw': {
          const parts = ['G2'];
          if (move.x !== undefined) parts.push(`X${fmt(move.x)}`);
          if (move.y !== undefined) parts.push(`Y${fmt(move.y)}`);
          if (move.z !== undefined) parts.push(`Z${fmt(move.z)}`);
          if (move.i !== undefined) parts.push(`I${fmt(move.i)}`);
          if (move.j !== undefined) parts.push(`J${fmt(move.j)}`);
          if (move.f !== undefined) parts.push(`F${Math.round(move.f)}`);
          emit(`${n()}${parts.join(' ')}`);
          modalG = 'G2';
          break;
        }
        case 'arc_ccw': {
          const parts = ['G3'];
          if (move.x !== undefined) parts.push(`X${fmt(move.x)}`);
          if (move.y !== undefined) parts.push(`Y${fmt(move.y)}`);
          if (move.z !== undefined) parts.push(`Z${fmt(move.z)}`);
          if (move.i !== undefined) parts.push(`I${fmt(move.i)}`);
          if (move.j !== undefined) parts.push(`J${fmt(move.j)}`);
          if (move.f !== undefined) parts.push(`F${Math.round(move.f)}`);
          emit(`${n()}${parts.join(' ')}`);
          modalG = 'G3';
          break;
        }
        case 'dwell': {
          emit(`${n()}G4 P${move.p}`);
          break;
        }
      }
    }
  }

  // ── Program Footer ──────────────────────────────────────────────────────────
  emit('');
  emit(`(--- End of Program ---)`);
  emit(`${n()}M5 (Spindle off)`);
  if (cfg.coolant !== 'off') emit(`${n()}M9 (Coolant off)`);
  if (cfg.homeAtEnd) {
    emit(`${n()}G0 Z${fmt(cfg.toolChangeZ)}`);
    emit(`${n()}G0 X${fmt(cfg.homeX)} Y${fmt(cfg.homeY)}`);
  } else {
    emit(`${n()}G0 Z${fmt(cfg.safeZ)} (Safe Z)`);
  }

  if (cfg.programFooter) {
    emit('');
    for (const fLine of cfg.programFooter.split('\n')) emit(fLine);
  }

  emit(`${n()}M30 (End of program)`);
  emit('%');

  return lines.join('\n');
}

export function estimateCycleTime(operations) {
  let totalSeconds = 0;
  const RAPID_SPEED = 5000; // mm/min assumed rapid

  for (const op of operations) {
    if (!op.enabled || !op.toolpath?.moves) continue;
    let prevX = 0, prevY = 0, prevZ = 25;

    for (const move of op.toolpath.moves) {
      const dx = (move.x ?? prevX) - prevX;
      const dy = (move.y ?? prevY) - prevY;
      const dz = (move.z ?? prevZ) - prevZ;
      const dist = Math.hypot(dx, dy, dz);

      if (move.type === 'rapid') {
        totalSeconds += (dist / RAPID_SPEED) * 60;
      } else if (move.type === 'feed') {
        const f = move.f || op.params?.feedRate || 1000;
        totalSeconds += (dist / f) * 60;
      } else if (move.type === 'dwell') {
        totalSeconds += (move.p || 0) / 1000;
      }

      if (move.x !== undefined) prevX = move.x;
      if (move.y !== undefined) prevY = move.y;
      if (move.z !== undefined) prevZ = move.z;
    }
  }

  return totalSeconds;
}

export function formatTime(seconds) {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) return `${h}h ${m}m ${s}s`;
  if (m > 0) return `${m}m ${s}s`;
  return `${s}s`;
}
