// V-Carve Medial-Spine Single Pass.
//
// Drives the tool along the true 3D centerline of each stroke in one fluid
// pass. No waterline rings — each XY position is cut exactly once at its
// full correct depth.
//
// Algorithm:
//   1. Run inward offsets in fine steps (R = i × stepR).
//   2. At each step compare vertex sets with the previous level.
//      Any vertex that has no close counterpart in the next level has
//      "collapsed" — the polygon boundary shrank past that point.
//      Those vertices are the medial-axis spine at depth Z = -R/tan(θ).
//   3. When all paths vanish, the last surviving vertices are also spine tips.
//   4. Order spine points with nearest-neighbour (starting from deepest).
//   5. Emit one continuous 3-D G-code path; retract only where gaps are large.

import {
  offsetPolyline,
  differencePolygonsOuter,
  isClockwise,
  stripClose,
} from './offset.js';

// ── Geometry helpers ──────────────────────────────────────────────────────────

function dist2(a, b) { return (a.x - b.x) ** 2 + (a.y - b.y) ** 2; }

// ── Tool-center path computation ──────────────────────────────────────────────

function computeValidPaths(outer, holes, R) {
  const so = offsetPolyline(outer, R, true);
  if (!so?.length) return [];
  const vo = so.filter(r => r?.length >= 3);
  if (!vo.length) return [];
  if (!holes?.length) return vo;
  const eh = holes.flatMap(h => offsetPolyline(h, -R, true)).filter(r => r?.length >= 3);
  if (!eh.length) return vo;
  const res = [];
  for (const oc of vo) {
    for (const p of differencePolygonsOuter(oc, eh)) if (p?.length >= 3) res.push(p);
  }
  return res;
}

// ── Spine extraction ──────────────────────────────────────────────────────────

// Returns {x, y, z}[] — unordered medial-axis sample points.
// For each vertex in the previous offset level, if no vertex in the current
// level lies within COLLAPSE_DIST, that vertex is on the collapsing boundary
// (i.e., the medial axis) at depth Z = -prevR / tan(θ).
function extractSpine(outer, holes, tanAngle, stepR, maxDepth) {
  const maxSteps = Math.ceil(maxDepth / stepR);
  const COLLAPSE_SQ = (3 * stepR) ** 2;
  const spine = [];

  let prevVerts = [];
  let prevR = 0;

  for (let i = 1; i <= maxSteps; i++) {
    const R = i * stepR;
    const paths = computeValidPaths(outer, holes, R);

    if (!paths.length) {
      const z = -prevR / tanAngle;
      for (const v of prevVerts) spine.push({ x: v.x, y: v.y, z });
      break;
    }

    const currVerts = paths.flatMap(p => stripClose([...p]));

    if (prevVerts.length > 0) {
      const z = -prevR / tanAngle;
      for (const v of prevVerts) {
        let near = false;
        for (const c of currVerts) {
          if (dist2(v, c) < COLLAPSE_SQ) { near = true; break; }
        }
        if (!near) spine.push({ x: v.x, y: v.y, z });
      }
    }

    prevVerts = currVerts;
    prevR = R;
  }

  return spine;
}

// For each convex corner in the outer polygon with interior angle ≤ angleThreshold,
// project the angle bisector inward and generate branch points from the corner (Z=0)
// down to the depth of the nearest rawSpine vertex within 6 mm.
//
// This fills the approach path that extractSpine structurally misses: Clipper's inward
// offset shifts the outer wall of a narrow arm inward by R, so the collapsed spine
// vertex sits at the shifted position (e.g. y=−5.55 for a bottom wall originally at
// y=−7 after R=1.45 mm). The physical corner at Z=0 is never generated by the
// collapse-detection loop. Corner branches connect the two.
function cornerBranches(outerPolygon, rawSpine, tanAngle, angleThreshold = Math.PI / 2) {
  if (!rawSpine.length) return [];
  const n = outerPolygon.length;
  const SEARCH_SQ   = 36;   // 6 mm radius
  const BRANCH_STEP = 0.05; // mm between branch sample points
  const branches = [];

  for (let i = 0; i < n; i++) {
    const prev = outerPolygon[(i + n - 1) % n];
    const curr = outerPolygon[i];
    const next = outerPolygon[(i + 1) % n];

    const aLen = Math.hypot(prev.x - curr.x, prev.y - curr.y);
    const bLen = Math.hypot(next.x - curr.x, next.y - curr.y);
    if (aLen < 1e-9 || bLen < 1e-9) continue;

    // Unit vectors from curr toward prev and next
    const adx = (prev.x - curr.x) / aLen, ady = (prev.y - curr.y) / aLen;
    const bdx = (next.x - curr.x) / bLen, bdy = (next.y - curr.y) / bLen;

    // In a CCW polygon, a convex corner has cross(ad, bd) < 0
    const cross = adx * bdy - ady * bdx;
    if (cross >= 0) continue; // reflex or collinear — skip

    const dot   = adx * bdx + ady * bdy;
    const angle = Math.atan2(-cross, dot); // interior angle ∈ (0, π]
    if (angle > angleThreshold) continue;

    // Angle bisector direction into polygon interior
    const bisRawX = adx + bdx, bisRawY = ady + bdy;
    const bisLen  = Math.hypot(bisRawX, bisRawY);
    if (bisLen < 1e-9) continue;
    const bx = bisRawX / bisLen, by = bisRawY / bisLen;

    // sin(half-angle): perpendicular-to-wall distance per unit bisector length
    const sinHalf = Math.sin(angle / 2);

    // Find the rawSpine vertex that lies most directly along the bisector ray:
    // must be in the forward half-space, within SEARCH_RADIUS, and have the
    // smallest perpendicular distance from the bisector line (≤ PERP_MAX mm).
    // Using the perp constraint avoids grabbing deep body-ring vertices that
    // happen to be nearby but are off to the side of the bisector direction.
    const PERP_MAX = 2.0;
    let bestPerp = Infinity, targetZ = 0;
    for (const sv of rawSpine) {
      const dx = sv.x - curr.x, dy = sv.y - curr.y;
      if (dx * dx + dy * dy > SEARCH_SQ) continue;
      const proj = dx * bx + dy * by;
      if (proj < 0.05) continue; // must be forward along bisector
      const perp = Math.abs(dx * by - dy * bx);
      if (perp < bestPerp) { bestPerp = perp; targetZ = sv.z; }
    }
    if (bestPerp > PERP_MAX || targetZ >= 0) continue; // no suitable target

    // Bisector distance to reach targetZ: (hitT × sinHalf) / tanAngle = |targetZ|
    const hitT = (-targetZ * tanAngle) / sinHalf;
    if (hitT < 0.1) continue;

    // Emit branch points from corner (Z=0) to bisector endpoint (Z=deepestZ)
    const steps = Math.max(5, Math.ceil(hitT / BRANCH_STEP));
    for (let s = 0; s <= steps; s++) {
      const t = (s / steps) * hitT;
      branches.push({ x: curr.x + t * bx, y: curr.y + t * by, z: -(t * sinHalf) / tanAngle });
    }
  }

  return branches;
}

// Order spine points nearest-neighbour, starting from the deepest point.
function orderSpine(pts) {
  if (!pts.length) return [];

  let startIdx = 0;
  for (let i = 1; i < pts.length; i++) {
    if (pts[i].z < pts[startIdx].z) startIdx = i;
  }

  const rem = [...pts];
  const out = [];
  let cur = rem.splice(startIdx, 1)[0];
  out.push(cur);

  while (rem.length) {
    let bestD = Infinity, bestI = -1;
    for (let i = 0; i < rem.length; i++) {
      const d = dist2(rem[i], cur);
      if (d < bestD) { bestD = d; bestI = i; }
    }
    cur = rem.splice(bestI, 1)[0];
    out.push(cur);
  }

  return out;
}

// ── G-code generation ─────────────────────────────────────────────────────────

export function generateGCode(spinePoints, config) {
  const {
    safeZ      = 5.0,
    feedRate   = 1499,
    plungeRate = 305,
    spindleRPM = 18000,
    rapidGap   = 2.0,
  } = config;
  const fmt = v => v.toFixed(4);
  const rapidGapSq = rapidGap * rapidGap;

  const lines = [
    '; V-Carve — MassoCAM Medial-Spine Single Pass',
    'G21', 'G90',
    `S${spindleRPM} M03`,
    `G00 Z${fmt(safeZ)}`,
  ];

  if (spinePoints.length >= 2) {
    lines.push(`G00 X${fmt(spinePoints[0].x)} Y${fmt(spinePoints[0].y)}`);
    lines.push(`G01 Z${fmt(spinePoints[0].z)} F${plungeRate}`);

    for (let i = 1; i < spinePoints.length; i++) {
      const prev = spinePoints[i - 1];
      const curr = spinePoints[i];
      if (dist2(curr, prev) > rapidGapSq) {
        lines.push(`G00 Z${fmt(safeZ)}`);
        lines.push(`G00 X${fmt(curr.x)} Y${fmt(curr.y)}`);
        lines.push(`G01 Z${fmt(curr.z)} F${plungeRate}`);
      } else {
        lines.push(`G01 X${fmt(curr.x)} Y${fmt(curr.y)} Z${fmt(curr.z)} F${feedRate}`);
      }
    }

    lines.push(`G00 Z${fmt(safeZ)}`);
  }

  lines.push('M05', 'M30');
  return lines.join('\n');
}

// ── Public API ────────────────────────────────────────────────────────────────

export function computeVCarveToolpath(outerPolygon, innerHoles = [], config = {}) {
  const {
    depthStep       = 0.05,
    maxDepth        = 25.0,
    bitHalfAngleDeg = 45,
    safeZ           = 5.0,
    feedRate        = 1499,
    plungeRate      = 305,
    spindleRPM      = 18000,
  } = config;

  const tanAngle = Math.tan(bitHalfAngleDeg * Math.PI / 180);
  const outer = isClockwise(outerPolygon) ? [...outerPolygon].reverse() : outerPolygon;
  const holes = innerHoles.map(h => isClockwise(h) ? [...h].reverse() : h);

  const rawSpine = extractSpine(outer, holes, tanAngle, depthStep, maxDepth);
  const branches = cornerBranches(outer, rawSpine, tanAngle);
  const spineVertices = orderSpine([...rawSpine, ...branches]);

  const gcode = generateGCode(spineVertices, { safeZ, feedRate, plungeRate, spindleRPM });
  const segments = spineVertices.length >= 2 ? [spineVertices] : [];

  return { spineVertices, segments, gcode };
}
